### ISSUE TITLE
Need link inspector

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/collaborative_workflow#154]
I noticed that some links (e.g., Code Review link in the image) are not working. Maybe we can add a GHA (e.g., [Linkspector](https://github.com/UmbrellaDocs/linkspector)) to check for broken links.

_Originally posted by @Bai-Li-NOAA in https://github.com/NOAA-FIMS/collaborative_workflow/issues/153#issuecomment-2356711986_

**Comment by kellijohnson-NOAA** [comment]
Some potential methods to get this done.

```
name: Check for Broken Links

# This action will run whenever you push new code to your main branch
on:
  push:
    branches:
      - main
  # You can also run it on a schedule (e.g., every Monday at 1 AM)
  # schedule:
  #   - cron: '0 1 * * 1'

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build the static site (customize this part)
      # This example is for a simple static site.
      # If you use Jekyll, Hugo, etc., you need to replace this step
      # with the appropriate build commands to generate your _site directory.
      # Example for Jekyll:
      # - name: Build Jekyll site
      #   uses: actions/jekyll-build-pages@v1
      #   with:
      #     source: './'
      #     destination: './_site'

      # Step 3: Run the broken link checker
      - name: Check for broken links
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          # Define the target to scan. We scan the entire repository.
          # The 'lycheeverse/lychee-action' will automatically find files
          # like markdown and HTML, so you don't need to specify a directory.
          args: .

      # Step 4: Add a summary report to the workflow run
      # This step makes the output of the link checker easy to read
      - name: Fail if there are broken links
        if: steps.lychee.outputs.exit_code == 1
        run: |
          echo "## 🚨 Broken Links Found" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.lychee.outputs.summary }}" >> $GITHUB_STEP_SUMMARY
          exit 1
```

I will be moving this issue to our NOAA-FIMS.io site rather than here.
